/**
 * The agent app's chrome, in the two languages the team speaks. Arabic is the
 * default: it is the language the agents work in. Same rule as the dashboard:
 * a lead's name and form answers are data and are never translated.
 */

export type AgentLang = "ar" | "en";

export const AGENT_TEXT = {
  ar: {
    appName: "دلني · الإيجنت",
    signInTitle: "تسجيل الدخول",
    signInSub: "ادخل بيانات الحساب اللي الأدمن عملهولك",
    username: "اسم المستخدم",
    password: "الباسورد",
    signIn: "دخول",
    signingIn: "بيدخل…",
    badCredentials: "اسم المستخدم أو الباسورد غلط",
    disabled: "الحساب ده موقوف. كلّم الأدمن.",
    network: "مفيش اتصال بالسيرفر. اتأكد من الإنترنت.",
    hello: "أهلاً",
    onShift: "متاح",
    offShift: "مش متاح",
    offShiftBanner: "إنت مش متاح دلوقتي، فمش هتوصلك ليدز جديدة. فعّل \"متاح\" لما تبدأ شغلك.",
    setupBanner: "كمّل إعداد التطبيق عشان التليفون يرن أول ما توصلك ليد",
    setupFix: "كمّل الإعداد",
    tabNew: "جديد",
    tabFollow: "متابعة",
    tabAll: "الكل",
    search: "دوّر بالاسم أو الرقم",
    emptyNew: "مفيش ليدز جديدة دلوقتي",
    emptyNewSub: "أول ما توصلك ليد تليفونك هيرن زي المكالمة",
    emptyFollow: "مفيش متابعات",
    emptyAll: "لسه مفيش ليدز اتوزعت عليك",
    waiting: "مستنية",
    assigned: "اتوزعت",
    call: "اتصل",
    callNow: "اتصل دلوقتي",
    whatsapp: "واتساب",
    logOutcome: "سجّل نتيجة المكالمة",
    formAnswers: "إجابات الفورم",
    source: "المصدر",
    campaign: "الكمبين",
    ad: "الإعلان",
    form: "الفورم",
    platform: "المنصة",
    history: "السجل",
    addNote: "اكتب ملاحظة…",
    save: "حفظ",
    saving: "بيحفظ…",
    saved: "اتسجل ✓",
    back: "رجوع",
    calls: (n: number) => (n === 1 ? "مكالمة واحدة" : `${n} مكالمات`),
    neverCalled: "لسه متصلتش",
    followUp: "المتابعة",
    followDue: "معاد المتابعة جه",
    // Outcome sheet
    whatHappened: "إيه اللي حصل في المكالمة؟",
    answered: "رد",
    noAnswer: "مردش",
    phoneOff: "مقفول / مش متاح",
    result: "النتيجة",
    qualified: "مؤهّل",
    notQualified: "مش مؤهّل",
    followUpNeeded: "محتاج متابعة",
    moreStages: "مراحل متقدمة",
    why: "السبب",
    reasons: ["مفيش ميزانية", "مش مهتم", "رقم غلط", "سمسار", "بيدور على إيجار", "منطقة تانية", "اشترى خلاص"],
    callAgain: "كلّمه تاني",
    inHour: "بعد ساعة",
    in3Hours: "بعد ٣ ساعات",
    tonight: "بالليل ٨",
    tomorrow: "بكرة ١٢ الضهر",
    custom: "وقت تاني",
    noReminder: "من غير تذكير",
    note: "ملاحظة (الفيدباك)",
    notePlaceholder: "اكتب اللي حصل في المكالمة…",
    dealValue: "قيمة الحجز (جنيه)",
    saveOutcome: "حفظ النتيجة",
    pickFirst: "اختار اللي حصل الأول",
    // Settings
    settings: "الإعدادات",
    account: "الحساب",
    setup: "إعداد الرنة",
    setupSub: "عشان التليفون يرن حتى وهو مقفول والتطبيق في الخلفية",
    permNotifications: "الإشعارات",
    permFullScreen: "الرنة على الشاشة كاملة",
    permBattery: "يشتغل في الخلفية من غير توفير بطارية",
    permCall: "الاتصال المباشر",
    ok: "تمام",
    fix: "فعّل",
    testRing: "جرّب الرنة",
    testRingSub: "اقفل الشاشة بعد ما تدوس، التليفون هيرن بعد ٥ ثواني",
    oemTip: "لو موبايلك شاومي أو أوبو أو ريلمي أو فيفو: من إعدادات التطبيق فعّل \"التشغيل التلقائي / Autostart\" وخلّي البطارية \"بدون قيود\".",
    webOnly: "إنت فاتح من المتصفح. عشان التليفون يرن لما توصلك ليد نزّل تطبيق أندرويد.",
    download: "تحميل التطبيق",
    language: "اللغة",
    logout: "تسجيل خروج",
    version: "الإصدار",
    refresh: "تحديث",
    justNow: "دلوقتي",
    minAgo: (n: number) => `من ${n} دقيقة`,
    hourAgo: (n: number) => `من ${n} ساعة`,
    dayAgo: (n: number) => `من ${n} يوم`,
    inMin: (n: number) => `بعد ${n} دقيقة`,
    inHourN: (n: number) => `بعد ${n} ساعة`,
    timelineCall: "اتصال",
    timelineWhatsapp: "واتساب",
    timelineAssign: "اتوزعت على",
    unnamed: "بدون اسم",
  },
  en: {
    appName: "Dlleni · Agent",
    signInTitle: "Sign in",
    signInSub: "Use the account your admin created for you",
    username: "Username",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in…",
    badCredentials: "Wrong username or password",
    disabled: "This account is disabled. Talk to your admin.",
    network: "Can't reach the server. Check your internet.",
    hello: "Hi",
    onShift: "On shift",
    offShift: "Off shift",
    offShiftBanner: "You're off shift, so no new leads will reach you. Switch to \"On shift\" when you start work.",
    setupBanner: "Finish setting up so your phone rings the moment a lead arrives",
    setupFix: "Finish setup",
    tabNew: "New",
    tabFollow: "Follow-up",
    tabAll: "All",
    search: "Search by name or number",
    emptyNew: "No new leads right now",
    emptyNewSub: "When one arrives your phone rings like a call",
    emptyFollow: "No follow-ups",
    emptyAll: "No leads have been handed to you yet",
    waiting: "Waiting",
    assigned: "Assigned",
    call: "Call",
    callNow: "Call now",
    whatsapp: "WhatsApp",
    logOutcome: "Log call result",
    formAnswers: "Form answers",
    source: "Source",
    campaign: "Campaign",
    ad: "Ad",
    form: "Form",
    platform: "Platform",
    history: "History",
    addNote: "Write a note…",
    save: "Save",
    saving: "Saving…",
    saved: "Saved ✓",
    back: "Back",
    calls: (n: number) => (n === 1 ? "1 call" : `${n} calls`),
    neverCalled: "Not called yet",
    followUp: "Follow-up",
    followDue: "Follow-up is due",
    whatHappened: "What happened on the call?",
    answered: "Answered",
    noAnswer: "No answer",
    phoneOff: "Phone off",
    result: "Result",
    qualified: "Qualified",
    notQualified: "Not qualified",
    followUpNeeded: "Needs follow-up",
    moreStages: "Later stages",
    why: "Reason",
    reasons: ["No budget", "Not interested", "Wrong number", "Broker", "Wants to rent", "Other area", "Already bought"],
    callAgain: "Call again",
    inHour: "In 1 hour",
    in3Hours: "In 3 hours",
    tonight: "Tonight 8pm",
    tomorrow: "Tomorrow noon",
    custom: "Pick a time",
    noReminder: "No reminder",
    note: "Note (feedback)",
    notePlaceholder: "What happened on the call…",
    dealValue: "Reservation value (EGP)",
    saveOutcome: "Save result",
    pickFirst: "Pick what happened first",
    settings: "Settings",
    account: "Account",
    setup: "Ringing setup",
    setupSub: "So the phone rings even when locked and the app is in the background",
    permNotifications: "Notifications",
    permFullScreen: "Full-screen ringing",
    permBattery: "Runs in background without battery saving",
    permCall: "Direct calling",
    ok: "OK",
    fix: "Turn on",
    testRing: "Test the ring",
    testRingSub: "Lock the screen after tapping; the phone rings in 5 seconds",
    oemTip: "On Xiaomi, Oppo, Realme or Vivo: in the app's settings turn on \"Autostart\" and set battery to \"No restrictions\".",
    webOnly: "You're in a browser. To have your phone ring when a lead arrives, install the Android app.",
    download: "Download the app",
    language: "Language",
    logout: "Sign out",
    version: "Version",
    refresh: "Refresh",
    justNow: "just now",
    minAgo: (n: number) => `${n}m ago`,
    hourAgo: (n: number) => `${n}h ago`,
    dayAgo: (n: number) => `${n}d ago`,
    inMin: (n: number) => `in ${n}m`,
    inHourN: (n: number) => `in ${n}h`,
    timelineCall: "Call",
    timelineWhatsapp: "WhatsApp",
    timelineAssign: "Assigned to",
    unnamed: "Unnamed",
  },
};

export type AgentText = (typeof AGENT_TEXT)["ar"];
