/**
 * The agent app's chrome, in the two languages the team speaks. Arabic is the
 * default: it is the language the agents work in. Same rule as the dashboard:
 * a lead's name and form answers are data and are never translated.
 */

export type AgentLang = "ar" | "en";

export const AGENT_TEXT = {
  ar: {
    appName: "دلني · الإيجنت",
    signInTitle: "تسجيل الدخول",
    signInSub: "ادخل بيانات الحساب اللي الأدمن عملهولك",
    username: "اسم المستخدم",
    password: "الباسورد",
    signIn: "دخول",
    signingIn: "بيدخل…",
    badCredentials: "اسم المستخدم أو الباسورد غلط",
    disabled: "الحساب ده موقوف. كلّم الأدمن.",
    network: "مفيش اتصال بالسيرفر. اتأكد من الإنترنت.",
    hello: "أهلاً",
    onShift: "متاح",
    offShift: "مش متاح",
    offShiftBanner: "إنت مش متاح دلوقتي، فمش هتوصلك ليدز جديدة. فعّل \"متاح\" لما تبدأ شغلك.",
    setupBanner: "كمّل إعداد التطبيق عشان التليفون يرن أول ما توصلك ليد",
    setupFix: "كمّل الإعداد",
    tabNew: "جديد",
    tabFollow: "متابعة",
    tabAll: "الكل",
    search: "دوّر بالاسم أو الرقم",
    emptyNew: "مفيش ليدز جديدة دلوقتي",
    emptyNewSub: "أول ما توصلك ليد تليفونك هيرن زي المكالمة",
    emptyFollow: "مفيش متابعات",
    emptyAll: "لسه مفيش ليدز اتوزعت عليك",
    waiting: "مستنية",
    assigned: "اتوزعت",
    call: "اتصل",
    callNow: "اتصل دلوقتي",
    whatsapp: "واتساب",
    logOutcome: "سجّل نتيجة المكالمة",
    formAnswers: "إجابات الفورم",
    source: "المصدر",
    campaign: "الكمبين",
    ad: "الإعلان",
    form: "الفورم",
    platform: "المنصة",
    history: "السجل",
    addNote: "اكتب ملاحظة…",
    save: "حفظ",
    saving: "بيحفظ…",
    saved: "اتسجل ✓",
    back: "رجوع",
    calls: (n: number) => (n === 1 ? "مكالمة واحدة" : `${n} مكالمات`),
    neverCalled: "لسه متصلتش",
    followUp: "المتابعة",
    followDue: "معاد المتابعة جه",
    // Outcome sheet
    whatHappened: "إيه اللي حصل في المكالمة؟",
    answered: "رد",
    noAnswer: "مردش",
    phoneOff: "مقفول / مش متاح",
    result: "النتيجة",
    qualified: "مؤهّل",
    notQualified: "مش مؤهّل",
    followUpNeeded: "محتاج متابعة",
    moreStages: "مراحل متقدمة",
    why: "السبب",
    reasons: ["مفيش ميزانية", "مش مهتم", "رقم غلط", "سمسار", "بيدور على إيجار", "منطقة تانية", "اشترى خلاص"],
    callAgain: "كلّمه تاني",
    inHour: "بعد ساعة",
    in3Hours: "بعد ٣ ساعات",
    tonight: "بالليل ٨",
    tomorrow: "بكرة ١٢ الضهر",
    custom: "وقت تاني",
    noReminder: "من غير تذكير",
    in15: "بعد ربع ساعة",
    in30: "بعد نص ساعة",
    in2Hours: "بعد ساعتين",
    callbackHint: "في المعاد ده التليفون هيرن زي المكالمة عشان تكلّمه تاني",
    note: "ملاحظة (الفيدباك)",
    notePlaceholder: "اكتب اللي حصل في المكالمة…",
    dealValue: "قيمة الحجز (جنيه)",
    saveOutcome: "حفظ النتيجة",
    pickFirst: "اختار اللي حصل الأول",
    // Settings
    settings: "الإعدادات",
    account: "الحساب",
    setup: "إعداد الرنة",
    setupSub: "عشان التليفون يرن حتى وهو مقفول والتطبيق في الخلفية",
    permNotifications: "الإشعارات",
    permFullScreen: "الرنة على الشاشة كاملة",
    permBattery: "يشتغل في الخلفية من غير توفير بطارية",
    permCall: "الاتصال المباشر",
    ok: "تمام",
    fix: "فعّل",
    testRing: "جرّب الرنة",
    testRingSub: "دوس، وبعدين اقفل التطبيق خالص (اسحبه من آخر التطبيقات) واقفل الشاشة. هيرن بعد ١٥ ثانية",
    oemTip: "لو موبايلك شاومي أو أوبو أو ريلمي أو فيفو: من إعدادات التطبيق فعّل \"التشغيل التلقائي / Autostart\" وخلّي البطارية \"بدون قيود\".",
    webOnly: "إنت فاتح من المتصفح. عشان التليفون يرن لما توصلك ليد نزّل تطبيق أندرويد.",
    download: "تحميل التطبيق",
    language: "اللغة",
    logout: "تسجيل خروج",
    version: "الإصدار",
    refresh: "تحديث",
    justNow: "دلوقتي",
    minAgo: (n: number) => `من ${n} دقيقة`,
    hourAgo: (n: number) => `من ${n} ساعة`,
    dayAgo: (n: number) => `من ${n} يوم`,
    inMin: (n: number) => `بعد ${n} دقيقة`,
    inHourN: (n: number) => `بعد ${n} ساعة`,
    timelineCall: "اتصال",
    timelineWhatsapp: "واتساب",
    timelineAssign: "اتوزعت على",
    unnamed: "بدون اسم",
    goodMorning: "صباح الخير",
    goodEvening: "مساء الخير",
    titleNew: "ليدز جديدة",
    titleFollow: "المتابعات",
    titleAll: "كل الليدز",
    today: "النهارده",
    waitingNow: "مستنية",
    calledToday: "اتصلت بيهم",
    medianToCall: "متوسط وقت الاتصال",
    min: "د",
    fast: "سريع",
    testChip: "تجربة",
    testLead: "ابعتلي ليد تجربة",
    testLeadSub: "ليد وهمية بترن على تليفونك خلال ١٥ ثانية. مش بتروح لميتا ولا 8X ولا التقارير.",
    testLeadSent: "اتبعتت ليد تجربة، اقفل الشاشة واستنى الرنة",
    tooManyTests: "بعت ليدز تجربة كتير، استنى شوية",
    testing: "التجربة",
    ringSettings: "الرنة",
    profile: "الحساب",
    step1: "١. المكالمة",
    step2: "٢. النتيجة",
    step3: "٣. المتابعة والملاحظة",
    selected: "متختار",
    phoneSetup: "تجهيز الموبايل",
    phoneSetupSub: "خطوات مرة واحدة عشان التليفون يرن حتى والتطبيق مقفول خالص",
    setupProgress: (done: number, total: number) => `${done} من ${total} خلصوا`,
    setupReady: "الموبايل جاهز يرن",
    setupReadySub: "جرّب دلوقتي: الرنة والتطبيق مقفول",
    stepNotifications: "اسمح بالإشعارات",
    stepNotificationsSub: "من غيرها مفيش رنة خالص",
    stepFullScreen: "اسمح بالرنة على الشاشة كاملة",
    stepFullScreenSub: "عشان تظهر فوق شاشة القفل زي المكالمة",
    stepBattery: "البطارية: بدون قيود",
    stepBatterySub: "اختار \"سماح / Allow\" في الرسالة اللي هتظهر",
    stepBackground: "اسمح بالشغل في الخلفية",
    stepBackgroundSub: "في صفحة التطبيق: البطارية ← بدون قيود (Unrestricted)",
    stepAutostart: "فعّل التشغيل التلقائي (Autostart)",
    stepAutostartSub: (maker: string) => `في موبايلات ${maker} دي أهم خطوة: دوّر على Dlleni Agent وفعّله`,
    stepPopup: "اسمح بالظهور فوق شاشة القفل",
    stepPopupSub: "فعّل \"Show on Lock screen\" و \"Display pop-up windows while running in the background\"",
    stepExact: "اسمح بالمنبهات والتذكيرات",
    stepExactSub: "عشان مواعيد المكالمات ترن في وقتها بالظبط",
    stepCall: "اسمح بالاتصال المباشر",
    stepCallSub: "اختياري: المكالمة تبدأ على طول من غير شاشة الطلب",
    lockRecents: "كمان: افتح آخر التطبيقات، اضغط مطوّل على Dlleni Agent واختار القفل 🔒 عشان الموبايل مايقفلوش",
    open: "افتح",
    opened: "اتفتح",
    testScheduled: "اقفل التطبيق والشاشة دلوقتي… هيرن بعد ١٥ ثانية",
    lastCheck: "آخر تواصل مع السيستم",
    notYet: "لسه",
    secondsAgo: (n: number) => `من ${n} ثانية`,
    checkTrouble: "التطبيق مش قادر يوصل للسيستم في الخلفية. راجع الخطوات اللي فوق",
  },
  en: {
    appName: "Dlleni · Agent",
    signInTitle: "Sign in",
    signInSub: "Use the account your admin created for you",
    username: "Username",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in…",
    badCredentials: "Wrong username or password",
    disabled: "This account is disabled. Talk to your admin.",
    network: "Can't reach the server. Check your internet.",
    hello: "Hi",
    onShift: "On shift",
    offShift: "Off shift",
    offShiftBanner: "You're off shift, so no new leads will reach you. Switch to \"On shift\" when you start work.",
    setupBanner: "Finish setting up so your phone rings the moment a lead arrives",
    setupFix: "Finish setup",
    tabNew: "New",
    tabFollow: "Follow-up",
    tabAll: "All",
    search: "Search by name or number",
    emptyNew: "No new leads right now",
    emptyNewSub: "When one arrives your phone rings like a call",
    emptyFollow: "No follow-ups",
    emptyAll: "No leads have been handed to you yet",
    waiting: "Waiting",
    assigned: "Assigned",
    call: "Call",
    callNow: "Call now",
    whatsapp: "WhatsApp",
    logOutcome: "Log call result",
    formAnswers: "Form answers",
    source: "Source",
    campaign: "Campaign",
    ad: "Ad",
    form: "Form",
    platform: "Platform",
    history: "History",
    addNote: "Write a note…",
    save: "Save",
    saving: "Saving…",
    saved: "Saved ✓",
    back: "Back",
    calls: (n: number) => (n === 1 ? "1 call" : `${n} calls`),
    neverCalled: "Not called yet",
    followUp: "Follow-up",
    followDue: "Follow-up is due",
    whatHappened: "What happened on the call?",
    answered: "Answered",
    noAnswer: "No answer",
    phoneOff: "Phone off",
    result: "Result",
    qualified: "Qualified",
    notQualified: "Not qualified",
    followUpNeeded: "Needs follow-up",
    moreStages: "Later stages",
    why: "Reason",
    reasons: ["No budget", "Not interested", "Wrong number", "Broker", "Wants to rent", "Other area", "Already bought"],
    callAgain: "Call again",
    inHour: "In 1 hour",
    in3Hours: "In 3 hours",
    tonight: "Tonight 8pm",
    tomorrow: "Tomorrow noon",
    custom: "Pick a time",
    noReminder: "No reminder",
    in15: "In 15 min",
    in30: "In 30 min",
    in2Hours: "In 2 hours",
    callbackHint: "At this time your phone rings like a call so you call them again",
    note: "Note (feedback)",
    notePlaceholder: "What happened on the call…",
    dealValue: "Reservation value (EGP)",
    saveOutcome: "Save result",
    pickFirst: "Pick what happened first",
    settings: "Settings",
    account: "Account",
    setup: "Ringing setup",
    setupSub: "So the phone rings even when locked and the app is in the background",
    permNotifications: "Notifications",
    permFullScreen: "Full-screen ringing",
    permBattery: "Runs in background without battery saving",
    permCall: "Direct calling",
    ok: "OK",
    fix: "Turn on",
    testRing: "Test the ring",
    testRingSub: "Tap, then close the app fully (swipe it away from recent apps) and lock the screen. It rings in 15 seconds",
    oemTip: "On Xiaomi, Oppo, Realme or Vivo: in the app's settings turn on \"Autostart\" and set battery to \"No restrictions\".",
    webOnly: "You're in a browser. To have your phone ring when a lead arrives, install the Android app.",
    download: "Download the app",
    language: "Language",
    logout: "Sign out",
    version: "Version",
    refresh: "Refresh",
    justNow: "just now",
    minAgo: (n: number) => `${n}m ago`,
    hourAgo: (n: number) => `${n}h ago`,
    dayAgo: (n: number) => `${n}d ago`,
    inMin: (n: number) => `in ${n}m`,
    inHourN: (n: number) => `in ${n}h`,
    timelineCall: "Call",
    timelineWhatsapp: "WhatsApp",
    timelineAssign: "Assigned to",
    unnamed: "Unnamed",
    goodMorning: "Good morning",
    goodEvening: "Good evening",
    titleNew: "New leads",
    titleFollow: "Follow-ups",
    titleAll: "All leads",
    today: "Today",
    waitingNow: "Waiting",
    calledToday: "Called",
    medianToCall: "Median time to call",
    min: "m",
    fast: "Fast",
    testChip: "Test",
    testLead: "Send me a test lead",
    testLeadSub: "A pretend lead that rings your phone within 15 seconds. It never reaches Meta, 8X or any report.",
    testLeadSent: "Test lead sent. Lock the screen and wait for the ring",
    tooManyTests: "Too many test leads, try again in a while",
    testing: "Testing",
    ringSettings: "Ringing",
    profile: "Profile",
    step1: "1. The call",
    step2: "2. The result",
    step3: "3. Follow-up and note",
    selected: "Selected",
    phoneSetup: "Phone setup",
    phoneSetupSub: "One-time steps so the phone rings even when the app is fully closed",
    setupProgress: (done: number, total: number) => `${done} of ${total} done`,
    setupReady: "This phone is ready to ring",
    setupReadySub: "Try it now: a ring with the app closed",
    stepNotifications: "Allow notifications",
    stepNotificationsSub: "Without them nothing can ring",
    stepFullScreen: "Allow full-screen ringing",
    stepFullScreenSub: "So it shows over the lock screen like a call",
    stepBattery: "Battery: no restrictions",
    stepBatterySub: "Choose \"Allow\" in the box that appears",
    stepBackground: "Allow background activity",
    stepBackgroundSub: "On the app's page: Battery → Unrestricted",
    stepAutostart: "Turn on Autostart",
    stepAutostartSub: (maker: string) => `On ${maker} phones this matters most: find Dlleni Agent and switch it on`,
    stepPopup: "Allow showing over the lock screen",
    stepPopupSub: "Turn on \"Show on Lock screen\" and \"Display pop-up windows while running in the background\"",
    stepExact: "Allow alarms & reminders",
    stepExactSub: "So callbacks ring at exactly the right minute",
    stepCall: "Allow direct calling",
    stepCallSub: "Optional: calls start without the dialer step",
    lockRecents: "Also: open recent apps, long-press Dlleni Agent and tap the lock 🔒 so the phone never closes it",
    open: "Open",
    opened: "Opened",
    testScheduled: "Close the app and lock the screen now… it rings in 15 seconds",
    lastCheck: "Last check with the server",
    notYet: "Not yet",
    secondsAgo: (n: number) => `${n}s ago`,
    checkTrouble: "The app can't reach the server in the background. Go through the steps above",
  },
};

export type AgentText = (typeof AGENT_TEXT)["ar"];
